logging:
  file: /aiclog/sktair-nugu-agent-poll/logs/nugu-agent-poll.log
  pattern:
    file: "%d %-5level --- [%thread] %logger{35} : %msg %n"

proxy-target.url-prefix: http://127.0.0.1:8853

# resource.static: /home/aicsvc/upon-demo/btv-demo/

management:
  server:
    port: 18086
  endpoints:
    web:
      base-path: /actuator
      path-mapping.health: health
      exposure:
        include: '*'
  health.elasticsearch.enabled: false
